### ISSUE TITLE
About user guide

### ISSUE THREAD

**Issue by ClassLNR** [georgian-io/pyoats#25]
I'm so interested in this project,but i find your community construction is incomplete, so could you provide some simple example for us?
such as a short code with short datasets. Expect your reply!

**Comment by angeliney** [comment]
Hi! Thank you for reaching out. You can find a sample code on tinyurl.com/pyoats-notebook 
and we also have [this blog](https://medium.com/@georgian-io/time-series-anomaly-detection-a-field-study-d13b35ee4344) which goes over each code section.
