### ISSUE TITLE
how to save the model trained with pyoats

### ISSUE THREAD

**Issue by goodoldday** [georgian-io/pyoats#43]
Hi,
I'm using pyoats library, but I cannot find a way in your doc to save the trained model after fitting so that I can decide the best hyperparameters, is there a way to save it?

**Comment by angeliney** [comment]
Hi! Unfortunately, we don't have any specific ways right now to save all the models other than pickling them. If you're using a dart-based model, you can use darts function to save by `your_model.model.save(file_name)`
